name: artifact
on: push

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    stpes:
      - name: echo
        run: echo hello-world > hello.txt
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-test
          paths: ./hello.txt

  download-artifact:
    runs-on: ubuntu-latest
    needs: [upload-artifact]
    stpes:
      - name: download artifact
        uese: actions/download-artifact@v3
        with:
          name: artifact-test
          path: ./
      - name: check
        run: cat hello.txt
